ALTER TABLE ICN_SFX
  MODIFY (
          ICN_SFX_IID   VARCHAR2(20) 
         );
         
ALTER TABLE ICN_SFX DROP column ICN_SFX_I_IID 
ALTER TABLE ICN_SFX DROP column ICN_SFX_RES_DATE
ALTER TABLE ICN_SFX DROP column ICN_SFX_RES_OPR