-- ITEM FLAT TABLE
CREATE TABLE ITEM_FLAT
  (
	-- INDENTIFIERS
    I_IID            VARCHAR2(10 BYTE) NOT NULL ENABLE,
    IID              VARCHAR2(12 BYTE) NOT NULL ENABLE,
    
	--REFER TO DATA DICTIONARY
	CICN             VARCHAR2(20 BYTE),
    CLNGTH           VARCHAR2(5 BYTE),
    CPAY             VARCHAR2(20 BYTE),
    CFLN             VARCHAR2(20 BYTE),
    CFLN_TYP         VARCHAR2(1 BYTE),
    EMPID            VARCHAR2(10 BYTE),
    EMPID_REC_TYP    VARCHAR2(1 BYTE),
    CICN_REC_TYP     VARCHAR2(1 BYTE),
    
	CSFX             VARCHAR2(20 BYTE),
    
	CDT_STMP1        VARCHAR2(7 BYTE),
    CTM_STMP1        VARCHAR2(9 BYTE),
    
	CENG             VARCHAR2(20 BYTE),
    
	CNUM_TYP1        VARCHAR2(5 BYTE),
    CNUM_TYP2        VARCHAR2(5 BYTE),
    CNUM_TYP3        VARCHAR2(5 BYTE),
    CFRM_TYP         VARCHAR2(20 BYTE),
    CSND_TO          VARCHAR2(1 BYTE),
    CSND_CNT         VARCHAR2(1 BYTE),
    CNSL_ERR         VARCHAR2(200 BYTE),
    CNSL_ERR_FILL_IN VARCHAR2(9 BYTE),
    
	CRSL_CLM_TYP     VARCHAR2(10 BYTE),
	OGPND			 VARCHAR2(20 BYTE),
	PRV_PND			 VARCHAR2(20 BYTE),
    CPND             VARCHAR2(20 BYTE),
    
	CCMMTS           VARCHAR2(68 BYTE),
    CSQ_STS          VARCHAR2(2 BYTE),
    CSQ_RTN_SYS      VARCHAR2(4 BYTE),
	CSQ_RTN_DT       VARCHAR2(8 BYTE),
	
    TINSFX           VARCHAR2(20 BYTE),
    CV2_NEMP_ID      VARCHAR2(10 BYTE),
    CV2_NEMP_POL     VARCHAR2(6 BYTE),
    CV2_NPAT_FNM     VARCHAR2(10 BYTE),
    CV2_NPAT_REL     VARCHAR2(2 BYTE),
    CV2_NENG         VARCHAR2(1 BYTE),
    CV2_NOFC         VARCHAR2(3 BYTE),
    CV2_NPLTFRM      VARCHAR2(1 BYTE),
    CPTP             VARCHAR2(20 BYTE),
    CV2_TRG_RS_CD    VARCHAR2(2 BYTE),
    CV2_ALT_ID       VARCHAR2(6 BYTE),
    CV2_MGR_OFC      VARCHAR2(2 BYTE),
    CV2_SYS_IND      VARCHAR2(4 BYTE),
    CORG             VARCHAR2(20 BYTE),
    CTYP             VARCHAR2(20 BYTE),
    CV2_SQ_DSG       VARCHAR2(1 BYTE),
    CV2_SFX_AMT       NUMBER(10,2),
    CAMT              NUMBER(10,2),
    CV2_POS          VARCHAR2(2 BYTE),
    CV2_MSVC_CD      VARCHAR2(6 BYTE),
    CV2_BLL_TYP      VARCHAR2(3 BYTE),
    CV2_FLN_DCC      VARCHAR2(3 BYTE),
    CRDT             VARCHAR2(20 BYTE),
    CEDT             VARCHAR2(20 BYTE),
    CSDT             VARCHAR2(20 BYTE),
	
	-- PATIENT DETAILS
    RELCD            VARCHAR2(2 BYTE),
    CV2_PAT_DOB      VARCHAR2(8 BYTE),
    PATNM            VARCHAR2(90 BYTE),
    CV2_PAT_M        VARCHAR2(10 BYTE),
    CV2_PAT_LNM      VARCHAR2(40 BYTE),
    CV2_PAT_ADR1     VARCHAR2(200 BYTE),
    CV2_PAT_ADR2     VARCHAR2(200 BYTE),
    CV2_PAT_CTY      VARCHAR2(100 BYTE),
    CV2_PAT_STE      VARCHAR2(2 BYTE),
    CV2_PAT_ZIP      VARCHAR2(9 BYTE),
    CV2_INS_DOB      VARCHAR2(8 BYTE),
    CV2_INS_FNM      VARCHAR2(40 BYTE),
    CV2_INS_M        VARCHAR2(10 BYTE),
    CV2_INS_LNM      VARCHAR2(40 BYTE),
    CV2_INS_ADR1     VARCHAR2(200 BYTE),
    CV2_INS_ADR2     VARCHAR2(200 BYTE),
    CV2_INS_CTY      VARCHAR2(100 BYTE),
    CV2_INS_STE      VARCHAR2(2 BYTE),
    CV2_INS_ZIP      VARCHAR2(9 BYTE),
    CV2_INS_ID       VARCHAR2(9 BYTE),
    
	CV2_POL_NO       VARCHAR2(20 BYTE),
    CPOL             VARCHAR2(6 BYTE),
	CPOLRSTRCTCD     VARCHAR2(2 BYTE),
    CMKT             VARCHAR2(20 BYTE),
    CPRD             VARCHAR2(20 BYTE),
    
	--PROVIDER DETAILS
	CV2_PRV_SSN      VARCHAR2(9 BYTE),
    PROVID           VARCHAR2(14 BYTE),
    CV2_PRV_DGR      VARCHAR2(4 BYTE),
    PROVNAME         VARCHAR2(36 BYTE),
    CV2_PRV_IND_FNM  VARCHAR2(10 BYTE),
    CV2_PRV_IND_LNM  VARCHAR2(30 BYTE),
    CV2_PRV_IND_INIT VARCHAR2(1 BYTE),
    CV2_PRV_ADR1     VARCHAR2(30 BYTE),
    CV2_PRV_ADR2     VARCHAR2(30 BYTE),
    CV2_PRV_CTY      VARCHAR2(15 BYTE),
    CV2_PRV_STE      VARCHAR2(2 BYTE),
    CV2_PRV_ZIP      VARCHAR2(9 BYTE),
    CV2_EPD_MTCH_CD  VARCHAR2(4 BYTE),
    CV2_CLM_CMMTS    VARCHAR2(103 BYTE),
    
	
    CRSKDT           VARCHAR2(8 BYTE),
	
	-- Transactional attributes
    CUROPER          VARCHAR2(6 BYTE),
    CURPT            VARCHAR2(6 BYTE),
    TOTPRIOR         NUMBER(22,0),
	CPRV             VARCHAR2(20 BYTE),
    CPWB             VARCHAR2(20 BYTE),
	RESOL_DATE DATE,
	
    CONSTRAINT PK_ITEM_FLAT PRIMARY KEY (IID) );

-- ICN SUFFIX TABLE
CREATE TABLE ICN_SFX
(
	ICN_SFX_I_IID  VARCHAR2(10 BYTE),
    ICN_SFX_IID    VARCHAR2(12 BYTE),
    ICN_SFX_ICN_ID VARCHAR2(11 BYTE) NOT NULL ENABLE,
    ICN_SFX_SFX    VARCHAR2(3 BYTE)  NOT NULL ENABLE,
	
	ICN_SFX_COD    VARCHAR2(10 BYTE),
    
	
	--TRANSACTIONAL ATTRIBUTES
    ICN_SFX_CRE_DATE DATE,
    ICN_SFX_UPD_DATE DATE,
	ICN_SFX_UPD_OPR VARCHAR2(6 BYTE),
	ICN_SFX_RES_DATE DATE,
    ICN_SFX_RES_OPR VARCHAR2(6 BYTE),
	ICN_SFX_FUN    VARCHAR2(10 BYTE),
	ICN_SFX_SFX_STA VARCHAR2(12 BYTE),
    
	CONSTRAINT PK_ICN_SFX PRIMARY KEY (ICN_SFX_ICN_ID, ICN_SFX_SFX, ICN_SFX_SFX_STA) );
	
	
-- ITEM FLAT STAGE
CREATE TABLE ITEM_FLAT_STAGE
  (
    ITEMID       NUMBER(10,0) NOT NULL ENABLE,
    I_IID        VARCHAR2(10 BYTE) NOT NULL ENABLE,
    IID          VARCHAR2(12 BYTE) NOT NULL ENABLE,
    CICN         VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CSFX         VARCHAR2(20 BYTE),
    MULTISFXIND  VARCHAR2(2 BYTE),
    CORG         VARCHAR2(20 BYTE),
    CPND         VARCHAR2(20 BYTE),
    CAMT         NUMBER(10,2),
    CPAY         VARCHAR2(20 BYTE),
    CENG         VARCHAR2(20 BYTE),
    CPOL         VARCHAR2(6 BYTE),
    CTYP         VARCHAR2(20 BYTE),
    CMKT         VARCHAR2(20 BYTE),
    PROVID       VARCHAR2(14 BYTE),
    CPOLRSTRCTCD VARCHAR2(2 BYTE),
    UPDATEMSGIND VARCHAR2(1 BYTE),
    EVALWB       VARCHAR2(1 BYTE),
    EVALPOINT    VARCHAR2(1 BYTE),
    EVALPRIORITY VARCHAR2(1 BYTE),
    CUR_TYP      VARCHAR2(20 BYTE),
    STS_UPD_IND  VARCHAR2(1 BYTE),
    ITEMSTATUS   VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CRE_OPR      VARCHAR2(128 BYTE),
    CRE_DATE DATE,
    UPD_OPR  VARCHAR2(128 BYTE),
    CFRM_TYP VARCHAR2(20 BYTE),
    CONSTRAINT PK_ITEM_ID PRIMARY KEY (ITEMID) 
  );